version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - immich_network

  # Redis (using Valkey as Redis alternative)
  redis:
    image: valkey/valkey:8-bookworm
    container_name: immich_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - immich_network

  # Immich Main Application
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - MACHINE_LEARNING_HOST=0.0.0.0
      - MACHINE_LEARNING_PORT=3003
      - MACHINE_LEARNING_WORKERS=1
      - MACHINE_LEARNING_WORKER_TIMEOUT=120
    volumes:
      - immich_config:/config
      - ./photos:/photos  # Change this to your photos path
      - ./libraries:/libraries  # Optional: external libraries
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - immich_network

# Named volumes for persistent data
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  immich_config:
    driver: local

# Network for service communication
networks:
  immich_network:
    driver: bridge
